name: Build

on:
  push:
    branches: [main]

jobs:
  build-to-deploy-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      # Installing node modules
      - name: Install Dependencies
        run: npm ci

      # Build Application
      - name: Build Application
        run: CI=false npm run build --prod

      # Docker Login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Building docker image and pushing to dockerhub
      - name: Build Image and Push to Dockerhub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          repository: ./
          file: ./Dockerfile
          push: true
          tags: devpatel29/notesapp-frontend:latest

      # Deploying to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: "./build"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
